name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        path: sample
    
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          repository: YuriAlcantara1995/DeployPipelineExample
         
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: sample
          path: sample
          
      - name: run deploy
        run: ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i qa.ini playbook.yml
    
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          repository: YuriAlcantara1995/M9-DevOps
      
      - name: login in docker hub
        run: docker  login --username yuriao --password ${{ secrets.DOCKER_KEY }}

      - name: build docker
        run: docker build . --tag yuriao/devops:latest

      - name: push docker      
        run: docker push yuriao/devops:latest
